### ISSUE TITLE
Override on ANDROID_JACK_VM_ARGS (?)

### ISSUE THREAD

**Issue by h4ndshake** [mikecriggs/fuckjack#2]
Take a look at lines 20,25 (auto-fuckjack.sh), and 42,47 (fuckjack.sh). Isn't the arguments we set earlier being overriden on the second var?

**Comment by marc2377** [comment]
Indeed it is. The correct should be

`export JACK_SERVER_VM_ARGUMENT=$ANDROID_JACK_VM_ARGS`

**Comment by mikecriggs** [comment]
Send a pull request if you guys would like to change anything. I'm sorry, I've been busy with other projects and life. Thank you :)
